import 'dart:convert';
import 'package:banking_app/services/connection_service.dart';
import 'package:crypto/crypto.dart';
import 'package:flutter/material.dart';
import 'package:web3auth_flutter/web3auth_flutter.dart';
import 'package:web3auth_flutter/enums.dart';
import 'package:web3auth_flutter/input.dart';
import 'package:web3auth_flutter/output.dart';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import 'package:web3dart/web3dart.dart';
import '../config/env.dart';

/// Result class for Web3Auth login
class Web3AuthResult {
  final bool success;
  final String walletAddress;
  final Map<String, dynamic>? userInfo;
  
  Web3AuthResult({
    required this.success,
    required this.walletAddress,
    this.userInfo,
  });
}

/// Web3Auth Service - Manages wallet creation and authentication
class Web3AuthService {
  static final Web3AuthService _instance = Web3AuthService._internal();
  factory Web3AuthService() => _instance;
  Web3AuthService._internal();
  static final Uri _redirectUrl = Uri.parse('canmawallet://auth');
  
  final _storage = const FlutterSecureStorage();
  
  String? _walletAddress;
  String? _privateKey;
  bool _isInitialized = false;
  
  String? get walletAddress => _walletAddress;
  bool get isInitialized => _isInitialized;
  
  /// Initialize Web3Auth
  Future<void> initialize() async {
    if (_isInitialized) {
      print('[Web3Auth] Already initialized');
      return;
    }
    
    try {
      // Check if Web3Auth Client ID is configured
      if (Env.web3AuthClientId == 'YOUR_WEB3AUTH_CLIENT_ID' || 
          Env.web3AuthClientId.isEmpty) {
        throw Exception(
          'Web3Auth Client ID belum dikonfigurasi!\n\n'
          'Silakan:\n'
          '1. Buka https://dashboard.web3auth.io\n'
          '2. Buat project baru atau pilih project yang ada\n'
          '3. Copy Client ID\n'
          '4. Update di lib/config/env.dart\n'
          '5. Rebuild aplikasi'
        );
      }
      
      print('[Web3Auth] ===== DEBUGGING WEB3AUTH INITIALIZATION =====');
      print('[Web3Auth] Client ID: ${Env.web3AuthClientId}');
      print('[Web3Auth] Network: ${Env.web3AuthNetwork}');
      print('[Web3Auth] Redirect URL: $_redirectUrl');

      final normalizedNetwork = Env.web3AuthNetwork.trim().toLowerCase();
      Network network;
      switch (normalizedNetwork) {
        case 'mainnet':
          network = Network.mainnet;
          break;
        case 'testnet':
          network = Network.testnet;
          break;
        case 'sapphire_devnet':
          network = Network.sapphire_devnet;
          break;
        default:
          network = Network.testnet;
          break;
      }
      
      print('[Web3Auth] Resolved network: $network');
      print('[Web3Auth] About to call Web3AuthFlutter.init()...');
      
      await Web3AuthFlutter.init(Web3AuthOptions(
        clientId: Env.web3AuthClientId,
        network: network,
        redirectUrl: _redirectUrl,
      ));
      
      print('[Web3Auth] Web3AuthFlutter.init() completed successfully');
      
      _isInitialized = true;
      print('[Web3Auth] Initialization successful');
      
      // Try to restore session
      await _restoreSession();
      if (_walletAddress != null) {
        print('[Web3Auth] Session restored: $_walletAddress');
      }
    } catch (e) {
      print('[Web3Auth] Initialization error: $e');
      throw Exception('Failed to initialize Web3Auth: $e');
    }
  }
  
  /// Generate wallet for user - HANYA Web3Auth (no fallback)
  /// Requires internet connection and Web3Auth service availability
  Future<Map<String, dynamic>> ensureUserWallet({String? firebaseUid, BuildContext? context}) async {
    try {
      print('[Web3Auth] Starting Web3Auth wallet generation for user: ${firebaseUid ?? 'unknown'}');
      print('[Web3Auth] 🚨 NO FALLBACK MODE - Web3Auth must succeed');
      
      // Check internet connection first
      final connectionService = ConnectionService();
      final hasInternet = await connectionService.hasInternetConnection();
      
      if (!hasInternet) {
        print('[Web3Auth] ❌ No internet connection detected');
        if (context != null) {
          connectionService.showConnectionErrorDialog(
            context,
            message: 'Internet connection is required to generate your wallet with Web3Auth.',
          );
        }
        throw Exception('No internet connection. Web3Auth requires internet access.');
      }
      
      // HANYA Web3Auth - no fallback allowed
      final result = await _tryWeb3AuthLogin();
      
      print('[Web3Auth] ✅ Web3Auth wallet creation SUCCESS');
      print('[Web3Auth] 🎯 CONFIRMED WALLET FROM WEB3AUTH: ${result['walletAddress']}');
      print('[Web3Auth] 🔐 This wallet was generated by Web3Auth, NOT fallback');
      
      return result;
    } catch (e) {
      print('[Web3Auth] ❌ Web3Auth wallet generation FAILED: $e');
      print('[Web3Auth] 🚨 No fallback - throwing error');
      
      // Show specific error dialog if context is provided
      if (context != null) {
        ConnectionService().showWeb3AuthErrorDialog(context, e.toString());
      }
      
      throw Exception('Web3Auth wallet creation failed (no fallback): $e');
    }
  }

  /// Try Web3Auth login
  Future<Map<String, dynamic>> _tryWeb3AuthLogin() async {
    print('[Web3Auth] ===== DEBUGGING WEB3AUTH LOGIN =====');
    await initialize();

    print('[Web3Auth] Starting Google login with Web3Auth...');
    print('[Web3Auth] Provider: ${Provider.google}');
    
    try {
      // Use Web3Auth native Google provider (updated API for 6.3.0)
      final response = await Web3AuthFlutter.login(LoginParams(
        loginProvider: Provider.google,
      )).timeout(
        const Duration(seconds: 30),
        onTimeout: () => throw Exception('Web3Auth login timeout after 30 seconds'),
      );
      
      print('[Web3Auth] ✓ Web3Auth login response received successfully');
      
      final privKey = response.privKey;
      final userInfo = response.userInfo;
      
      print('[Web3Auth] Private key received: ${privKey != null ? 'YES (${privKey.length} chars)' : 'NO'}');
      print('[Web3Auth] User info received: ${userInfo != null ? 'YES' : 'NO'}');
      
      if (privKey == null || privKey.isEmpty) {
        throw Exception('No private key received from Web3Auth response');
      }
      
      _privateKey = privKey;
      final ethKey = EthPrivateKey.fromHex(privKey);
      _walletAddress = ethKey.address.hexEip55;
      
      print('[Web3Auth] ✓ Generated wallet address: $_walletAddress');
      
      await _saveSession();
      print('[Web3Auth] ✓ Session saved successfully');
      
      // Convert userInfo to Map<String, dynamic> or handle as dynamic
      Map<String, dynamic> userInfoMap = {};
      if (userInfo != null) {
        // Extract basic info if available
        try {
          userInfoMap = {
            'email': userInfo.email,
            'name': userInfo.name,
            'profileImage': userInfo.profileImage,
            'typeOfLogin': userInfo.typeOfLogin,
          };
        } catch (e) {
          print('[Web3Auth] Error converting userInfo: $e');
        }
      }
      
      return {
        'success': true,
        'walletAddress': _walletAddress,
        'userInfo': userInfoMap,
        'method': 'web3auth'
      };
    } catch (e) {
      print('[Web3Auth] ✗ Login failed with error: $e');
      print('[Web3Auth] Error type: ${e.runtimeType}');
      
      // Check for specific redirect URL error
      final errorMsg = e.toString().toLowerCase();
      if (errorMsg.contains('redirect') || errorMsg.contains('whitelist') || errorMsg.contains('domain')) {
        print('[Web3Auth] 🚨 REDIRECT URL ERROR DETECTED!');
        print('[Web3Auth] This means canmawallet://auth is NOT whitelisted in Web3Auth dashboard');
        throw Exception('REDIRECT URL ERROR: Please whitelist canmawallet://auth in Web3Auth dashboard.\n\nOriginal error: $e');
      }
      
      rethrow;
    }
  }

  /// Generate deterministic wallet from Firebase UID
  Future<Map<String, dynamic>> _generateWalletFromSeed(String firebaseUid) async {
    print('[Web3Auth] Generating deterministic wallet from Firebase UID');
    
    // Create deterministic private key from Firebase UID
    final seed = 'canma_wallet_$firebaseUid';
    final seedBytes = utf8.encode(seed);
    final hash = sha256.convert(seedBytes);
    
    // Ensure we have valid private key format (32 bytes)
    final privateKeyHex = hash.toString();
    
    // Generate wallet
    final ethKey = EthPrivateKey.fromHex(privateKeyHex);
    final walletAddress = ethKey.address.hexEip55;
    
    _privateKey = privateKeyHex;
    _walletAddress = walletAddress;
    
    await _saveSession();
    
    return {
      'success': true,
      'walletAddress': walletAddress,
      'userInfo': null,
      'method': 'deterministic'
    };
  }

  /// Legacy method - calls ensureUserWallet
  Future<Map<String, dynamic>> loginWithGoogle() async {
    return await ensureUserWallet();
  }
  
  /// Method for new AuthService integration
  Future<Web3AuthResult> login() async {
    try {
      final result = await ensureUserWallet();
      return Web3AuthResult(
        success: result['success'] as bool,
        walletAddress: result['walletAddress'] as String,
        // Handle TorusUserInfo by converting to string or passing as dynamic
        userInfo: null, // Don't pass userInfo to avoid type errors
      );
    } catch (e) {
      print('[Web3Auth] Login failed: $e');
      return Web3AuthResult(
        success: false,
        walletAddress: '',
        userInfo: null,
      );
    }
  }

  /// Login / ensure wallet using Firebase JWT (works for email/password users too)
  Future<Map<String, dynamic>> loginWithFirebaseJwt() async {
    try {
      // Keep backwards-compatible API, but use Google provider to avoid JWT verifier issues
      return await loginWithGoogle();
    } catch (e) {
      throw Exception('Web3Auth wallet init failed: $e');
    }
  }
  
  /// Logout
  Future<void> logout() async {
    try {
      await Web3AuthFlutter.logout();
      await _clearSession();
      
      _walletAddress = null;
      _privateKey = null;
    } catch (e) {
      throw Exception('Logout failed: $e');
    }
  }
  
  /// Get private key (use carefully!)
  Future<String?> getPrivateKey() async {
    if (_privateKey != null) return _privateKey;
    return await _storage.read(key: 'web3auth_private_key');
  }
  
  /// Save session to secure storage
  Future<void> _saveSession() async {
    if (_privateKey != null && _walletAddress != null) {
      await _storage.write(key: 'web3auth_private_key', value: _privateKey);
      await _storage.write(key: 'wallet_address', value: _walletAddress);
    }
  }
  
  /// Restore session from secure storage
  Future<void> _restoreSession() async {
    _privateKey = await _storage.read(key: 'web3auth_private_key');
    _walletAddress = await _storage.read(key: 'wallet_address');
  }
  
  /// Clear session
  Future<void> _clearSession() async {
    await _storage.delete(key: 'web3auth_private_key');
    await _storage.delete(key: 'wallet_address');
  }
}


