// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9El9zFvC6Ou05LmXqK_nf1BTNsakjRcg',
    appId: '1:575615376354:web:d7d51b59c859d9f3ff37bb',
    messagingSenderId: '575615376354',
    projectId: 'canma-wallet',
    authDomain: 'canma-wallet.firebaseapp.com',
    storageBucket: 'canma-wallet.firebasestorage.app',
    measurementId: 'G-BPK4B14R9H',
    databaseURL: 'https://canma-wallet-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7O3Y3BPtz0zU2GKXHZQawhMact44UZwY',
    appId: '1:575615376354:android:79d3a45dbf102dd0ff37bb',
    messagingSenderId: '575615376354',
    projectId: 'canma-wallet',
    storageBucket: 'canma-wallet.firebasestorage.app',
    databaseURL: 'https://canma-wallet-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpFGIcIk7BVdbZIh9I5yUEGHNws82Ui5E',
    appId: '1:575615376354:ios:bdb3690ed6ffc8a5ff37bb',
    messagingSenderId: '575615376354',
    projectId: 'canma-wallet',
    storageBucket: 'canma-wallet.firebasestorage.app',
    iosBundleId: 'com.bankingapp.bankingApp',
    databaseURL: 'https://canma-wallet-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpFGIcIk7BVdbZIh9I5yUEGHNws82Ui5E',
    appId: '1:575615376354:ios:bdb3690ed6ffc8a5ff37bb',
    messagingSenderId: '575615376354',
    projectId: 'canma-wallet',
    storageBucket: 'canma-wallet.firebasestorage.app',
    iosBundleId: 'com.bankingapp.bankingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9El9zFvC6Ou05LmXqK_nf1BTNsakjRcg',
    appId: '1:575615376354:web:990a3bcb74d3d7a6ff37bb',
    messagingSenderId: '575615376354',
    projectId: 'canma-wallet',
    authDomain: 'canma-wallet.firebaseapp.com',
    storageBucket: 'canma-wallet.firebasestorage.app',
    measurementId: 'G-XELL3ZJQ3D',
  );
}
